apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fastapi.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platformcore.labels" . | nindent 4 }}
    app.kubernetes.io/component: fastapi
  {{- if .Values.fastapi.serviceAccount.roleARN }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.fastapi.serviceAccount.roleARN | quote }}
  {{- end }}