
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platformcore.labels" . | nindent 4 }}
    app.kubernetes.io/component: fastapi
spec:
  selector:
    {{- include "platformcore.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: fastapi
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
