#--------------------------------------------------------------------------------------------------------
# FASTAPI - SERVICE ACCOUNT
#--------------------------------------------------------------------------------------------------------


apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi
  namespace: platformcore
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::316053082971:role/platformcore-fastapi