#--------------------------------------------------------------------------------------------------------
# FASTAPI - SERVICE
#--------------------------------------------------------------------------------------------------------


apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: platformcore
spec:
  selector:
    app: fastapi
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP



