apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "platformcore.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
data:
  
  APP_ENV: {{ .Values.nginx.config.appEnv | quote }}
  LOG_LEVEL: {{ .Values.nginx.config.logLevel | quote }}

 
  nginx.conf: |
    server {
      listen 80;
      location /healthz {
        return 200 'OK';
        add_header Content-Type text/plain;
      }
      location /api/ {
        proxy_pass http://fastapi:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
      location / {
        return 200 'platformcore - k8s';
        add_header Content-Type text/plain;
      }
    }
