apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platformcore.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  selector:
    matchLabels:
        {{- include "platformcore.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        {{- include "platformcore.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/nginx/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: APP_ENV
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: LOG_LEVEL
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true
          resources: 
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: default.conf