apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platformcore.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  selector:
    {{- include "platformcore.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP