apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: platformcore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        env:
          - name: POSTGRES_USER
            valueFrom: 
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_USER
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
          - containerPort: 5432
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
        readinessProbe: 
          exec:
            command: ["pg_isready", "-U", "platformcore","-d","platformcore"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
          