apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: platformcore
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
