# charts/platformcore/templates/postgres/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platformcore.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: platformcore/app/postgres-password
        property: POSTGRES_PASSWORD